stages:
  - test
  - build
  - scan
  - deploy


test:
  stage: test
  image: docker:19.03.1
  script:
  # This configures the test stuff
  - apt-get update -qy
  - apt-get install -y python-dev python-pip
  - pip install -r src/requirements.txt
  - flake8 vuln_django --max-line-length=127
  - cd src
  - python manage.py test

docker-build:
  stage: build
  image: docker:19.03.1
  services:
    - docker:19.03.1-dind
  script:
    - docker build -t vuln_django:latest .

hawk_scan_execute:
  stage: scan
  image: docker:19.03.1
  services:
    - docker:19.03.1-dind
  script:
    - docker build -t vuln_django:latest .
    - docker network create scan_net
    - docker pull stackhawk/hawkscan:latest
    - docker run --detach -p 8020:8020 --name vuln_django --rm --network scan_net vuln_django:latest
    - |
      docker run --volume $(pwd):/hawk:rw --tty --rm --network scan_net \
        --env API_KEY="hawk.${HAWK_API_ID}.${HAWK_API_SECRET}" \
        --env NO_COLOR=true \
        stackhawk/hawkscan:latest stackhawk.yml stackhawk-gitlab.yml
