hawkscan:
  stage: hawkscan
  services:
    - docker:dind
  image: docker:latest
  before_script:
    - docker info
    - apk update
    - apk upgrade
    - apk add --no-cache docker-compose

  variables:
    GIT_STRATEGY: fetch
  allow_failure: true
  script:
    - docker pull stackhawk/hawkscan:latest
    - docker-compose up -d

    - |
      docker run --volume $(pwd):/hawk:rw --tty --rm \
        --network vuln_django_play_default \
        --env API_KEY="hawk.${HAWK_API_ID}.${HAWK_API_SECRET}" \
        stackhawk/hawkscan:latest $HAWKSCAN_ARGS
  artifacts:
    reports:
      dast: stackhawk-dast-report.json
